export const LOGOUT = 'LOGOUT';
export const LOGIN = 'LOGIN';
export const SET_PROVIDER = 'SET_PROVIDER';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';

export const USER_DATA = 'USER_DATA';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_FAILURE = 'USER_DATA_FAILURE';

export const OPEN_CHATBOX = 'OPEN_CHATBOX';
export const CLOSE_CHATBOX = 'CLOSE_CHATBOX';

export const OPEN_SEARCH_FRIEND = 'OPEN_SEARCH_FRIEND';
export const CLOSE_SEARCH_FRIEND = 'CLOSE_SEARCH_FRIEND';

export const SEARCH_FRIEND = 'SEARCH_FRIEND';
export const EMPTY_SEARCH_FRIEND = 'EMPTY_SEARCH_FRIEND';

export const OPEN_PROFILE = 'OPEN_PROFILE';
export const CLOSE_PROFILE = 'CLOSE_PROFILE';

export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_FAILURE = 'GET_CONVERSATIONS_FAILURE';

export const CREATE_CONVERSATION = 'CREATE_CONVERSATION';
export const CREATE_CONVERSATION_SUCCESS = 'CREATE_CONVERSATION_SUCCESS';
export const CREATE_CONVERSATION_FAILURE = 'CREATE_CONVERSATION_FAILURE';

export const GET_FRIEND_DETAILS = 'GET_FRIEND_DETAILS';
export const GET_FRIEND_DETAILS_SUCCESS = 'GET_FRIEND_DETAILS_SUCCESS';
export const GET_FRIEND_DETAILS_FAILURE = 'GET_FRIEND_DETAILS_FAILURE';

export const FIND_FRIEND = 'FIND_FRIEND';
export const FIND_FRIEND_SUCCESS = 'FIND_FRIEND_SUCCESS';
export const FIND_FRIEND_FAILURE = 'FIND_FRIEND_FAILURE';

export const EMPTY_FIND_FRIEND = 'EMPTY_FIND_FRIEND';


// Messages
export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_FAILURE = 'GET_MESSAGES_FAILURE';

export const SET_CURRENT_CONVERSATION = 'SET_CURRENT_CONVERSATION';

export const ADD_MESSAGE = 'ADD_MESSAGE';
export const ADD_MESSAGE_SUCCESS = 'ADD_MESSAGE_SUCCESS';
export const ADD_MESSAGE_FAILURE = 'ADD_MESSAGE_FAILURE';

export const SET_ARRIVAL_MESSAGE = 'SET_ARRIVAL_MESSAGE';
export const SET_TYPERS = 'SET_TYPERS';

export const SET_ONLINE_FRIENDS = 'SET_ONLINE_FRIENDS';
export const CHAT_LIST_FILTER = 'CHAT_LIST_FILTER';